title: Heguang Lin
logo: /assets/img/figure.jpg
description: University of Pennsylvania  hglin@seas.upenn.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
